### ISSUE TITLE
'cannot find role in /home/.../dresden-weekly.Rails/postgresql'

### ISSUE THREAD

**Issue by tnt** [dresden-weekly/ansible-rails-example#2]
I have put the full output into [this gist](https://gist.github.com/tnt/05e7d9967dcc8669b11a).

`find . -name postgresql` doesn't yield any result.

**Comment by arBmind** [comment]
Thank you for trying. It seems to be a legit bug.

Log analysis:
- the first run failed, because you do not have permission to modify files in /etc/ansible/roles
- the second run with sudo recognizes the ansible/.role/ folder and skips galaxy

Solution:
- you should not need sudo to install roles
- ANSIBLE_ROLES_PATH is not exported before ansible-galaxy was run.

Fix:
- added export ANSIBLE_ROLES_PATH 

Please try again.
**Please make sure you update git submodules and delete ansible/.roles/**

**Comment by tnt** [comment]
Thank you. Now I get [this error](https://gist.github.com/tnt/968357d091b054e7747f).

Maybe I don't get what you mean with "the vagrant keys" in the README. I'm using these: https://github.com/mitchellh/vagrant/tree/master/keys (?)

By the way: the `with_root` function in `git-install.sh` does never prompt for a password because `$PS1` seems to be never set in scripts. So the line

``` bash
elif [ -z "$PS1" ]; then
```

should probably better be replaced by something like

``` bash
elif [ "$(tty)" == "not a tty" ]; then
```

**Comment by arBmind** [comment]
git-install.sh was successfull for you. No problem there.

Your link to the vagrant keys is the right one. I always use an ssh-agent that provides keys and use forwarding to travel through vms. Maybe this setup is not a good requirement.

Solution options:
A) you add the vagrant key to your ssh-agent and allow agent forwarding
B) use "ansible_ssh_private_key_file" in the [hosts inventory](http://docs.ansible.com/intro_inventory.html)

Please try option B. The resulting PR might help everyone! I will try it the next time I boot my machine, which might take a while.

**Comment by tnt** [comment]
The reason for the alleged _SSH error_ seems to be simply that at this point there is neither any VM running nor even created. (My ssh-agent forwarding is definitely working.)

I'm suspecting that the trueness of the claim that this runs in "A shell that can run ... Bash shell scripts" is not the only thing in the README that is say _incomplete_. Did you really ever run this successfully on a Linux system?

**Comment by arBmind** [comment]
You caught me. It ran once on Linux / MacOS, but I cannot test every version. The last trials were conducted weeks ago...

We will investigate this as soon as possible.

**Comment by tnt** [comment]
Sorry for bothering you.I have reactivated an old Mac mini and upgraded an Ubuntu install today to 14.04 to have a more common system for testing. I'll try to find time to dig deeper in what the scripts and of course ansible, vagrant a.s.o. do and hope that I will sooner or later be able to contribute something useful. But I'm a little bit in trouble to try to get certain _reasonable_ things done. My _improvable_ Bash skills are probably my least problem.

I hope to see you on wednesday at the GCHQ. Last wednesday I've been the only dresden-weekly participant. - I'll watch the calendar this time.

**Comment by arBmind** [comment]
We found and fixed a bug, this weekend. Vagrant 1.7 has introduced more secure connections. I disabled this feature for now. Maybe this is already the solution.

Sorry, that I was not there last Wednesday. The FSFW-Dresden (Freie Software & Freies Wissen Dresden) meeting is every second week. This week, I will be there.
